// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBwPjABTB0dfQzRXohgtvN0c2SOYhjZrs',
    appId: '1:973406003505:web:e0b1c4116ae36c7daa1010',
    messagingSenderId: '973406003505',
    projectId: 'ride-sharing-app-ee4aa',
    authDomain: 'ride-sharing-app-ee4aa.firebaseapp.com',
    storageBucket: 'ride-sharing-app-ee4aa.firebasestorage.app',
    measurementId: 'G-73M2TTF6C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd4bhHaUvoGHlAhYGiWjmEoh_cre4KsuQ',
    appId: '1:973406003505:android:dae243c72ac3370caa1010',
    messagingSenderId: '973406003505',
    projectId: 'ride-sharing-app-ee4aa',
    storageBucket: 'ride-sharing-app-ee4aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhHgjP1HBZRkJNHNfLNaDfFUo8XU_rMaQ',
    appId: '1:973406003505:ios:af50670d832900b2aa1010',
    messagingSenderId: '973406003505',
    projectId: 'ride-sharing-app-ee4aa',
    storageBucket: 'ride-sharing-app-ee4aa.firebasestorage.app',
    iosBundleId: 'com.anstopcovoiturage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhHgjP1HBZRkJNHNfLNaDfFUo8XU_rMaQ',
    appId: '1:973406003505:ios:a5978c63fd4931bbaa1010',
    messagingSenderId: '973406003505',
    projectId: 'ride-sharing-app-ee4aa',
    storageBucket: 'ride-sharing-app-ee4aa.firebasestorage.app',
    iosBundleId: 'com.example.rideSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBwPjABTB0dfQzRXohgtvN0c2SOYhjZrs',
    appId: '1:973406003505:web:8c25fa4f604490b9aa1010',
    messagingSenderId: '973406003505',
    projectId: 'ride-sharing-app-ee4aa',
    authDomain: 'ride-sharing-app-ee4aa.firebaseapp.com',
    storageBucket: 'ride-sharing-app-ee4aa.firebasestorage.app',
    measurementId: 'G-8WW5RS0W26',
  );
}
